name: Deploy WordPress Theme/Plugin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.http://13.207.64.83/ }}
          username: deploy
          key: ${{ secrets.l/twow4brWzy1B6ixojFyvQVBTRAnJSLV2Ud2DGa }}
          source: "wp-content/themes/twentytwentyfour/*"
          target: "/var/www/html/wp-content/themes/twentytwentyfour/"
